;------------------------
; Used ISAR registers
;------------------------

CACTUS_X_REG		= 	050		; #40
BIRD_X_REG			= 	051		; #41

CACTUS_CLEAR_FLAG_REG	= 052	; #42
CACTUS_CURRENT_SPRITE_REG	= 053	;#43

DINO_JUMP_STATE_REG	=	054		; #44
DINO_JUMP_COUNTER_REG	= 055	; #45
DINO_Y_REG			=	060		; #48
DINO_STATE_REG 		= 	061		; #49

CLOCK_DINO_ANIMATION_REG 	= 062		; #50
CLOCK_DINO_MOVE_REG			= 063		; #51
CLOCK_FIELD_REG				= 064		; #52
CLOCK_BIRD_REG				= 065		; #53

TIMING_DINO_ANIMATION	= 5
TIMING_DINO_MOVE		= 1
TIMING_FIELD			= 1
TIMING_BIRD				= 1

CACTUS_START_POSITION 		= 110
CACTUS_SPRITE_INDEX_START 	= 3
CACTUS_SPRITE_INDEX_END 	= 6

DINO_JUMP_STATE_RUN		= 0
DINO_JUMP_STATE_UP		= 1
DINO_JUMP_STATE_DOWN	= 2

DINO_JUMP_HEIGHT		= 17

;------------------------
; Sprites sizes
;------------------------

DINO_SPRITE_WIDTH 		= 8
DINO_SPRITE_HEIGHT 		= 11

CACTUS_SPRITE_WIDTH 	= 8
CACTUS_SPRITE_HEIGHT 	= 7

BIRD_SPRITE_WIDTH		= 8
BIRD_SPRITE_HEIGHT		= 5

;;;;;;;;;;;;;;;;;;

GROUND_START 		= 44

DINO_X_POSITION 	= 25

CACTUS_Y_POSITION 	= 34

BIRD_Y_POSITION		= 20

;;;;;;;;;;;;;;;;;;

