;------------------------
; Used ISAR registers
;------------------------

CACTUS_X_REG		= 	050
BIRD_X_REG			= 	051

CACTUS_CLEAR_FLAG_REG	= 052
CACTUS_CURRENT_SPRITE_REG	= 053

DINO_JUMP_STATE_REG	=	054
DINO_JUMP_COUNTER_REG	= 055
DINO_Y_REG			=	060
DINO_STATE_REG 		= 	061

; 
CLOCK_DINO_ANIMATION_REG 	= 062
CLOCK_DINO_MOVE_REG			= 063
CLOCK_FIELD_REG				= 064
CLOCK_BIRD_REG				= 065

GAME_OVER_CYCLE_REG = 070

;;;;;;;;;;;;;;;;;;

TIMING_DINO_ANIMATION	= 5
TIMING_DINO_MOVE		= 1
TIMING_FIELD			= 1
TIMING_BIRD				= 1

CACTUS_START_POSITION 		= 110


DINO_JUMP_STATE_RUN		= 0
DINO_JUMP_STATE_UP		= 1
DINO_JUMP_STATE_DOWN	= 2

DINO_JUMP_HEIGHT		= 17

;------------------------
; World
;------------------------

COLOR_SKY = COLOR_CLEAR_TO_BLUE

SPRITE_DINO_BORDER      = 2
SPRITE_DINO_CLEAR       = 3
SPRITE_CACTUS_CLEAR     = 4
SPRITE_CACTUS_FIRST 	= 5
SPRITE_CACTUS_LAST      = 8
SPRITE_CACTUS_BORDER    = 8

COLLISION_ANIMATION_CYCLES  = 2
COLLISION_ANIMATION_DELAY   = 150

;------------------------
; Sprites sizes
;------------------------

DINO_SPRITE_WIDTH 		= 8
DINO_SPRITE_HEIGHT 		= 11

CACTUS_SPRITE_WIDTH 	= 8
CACTUS_SPRITE_HEIGHT 	= 8

BIRD_SPRITE_WIDTH		= 8
BIRD_SPRITE_HEIGHT		= 5

;;;;;;;;;;;;;;;;;;

GROUND_START_Y      = 45
GROUND_END_Y        = 63

DINO_X_POSITION 	= 25

CACTUS_Y_POSITION 	= 33

BIRD_Y_POSITION		= 20

;;;;;;;;;;;;;;;;;;

